# Generated by Django 3.2 on 2023-04-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20230406_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='color',
        ),
    ]
